version: "3.8"
services:
  web:
    build:
      context: ./web
    command: bash -c "npm install && npm run dev"
    volumes:
      - './web:/web'
    ports:
      - 3000:3000
    stdin_open: true
    env_file:
      - ./.env